### Initial Data Loading and Cleaning

Loading all the required libraries

In [3]:
#libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import numpy as np

In [4]:
#define relative path to dataset
path_train = '../data/external/sign_mnist_train.csv'
path_test = '../data/external/sign_mnist_test.csv'

#define image resolution 
res = (28,28)

In [5]:
#saving data into pandas dataframes 
train = pd.read_csv(path_train)
test = pd.read_csv(path_test)

In [6]:
#printing shape
print(f'Train Shape:{train.shape}')
print(f'Test Shape:{test.shape}')

Train Shape:(27455, 785)
Test Shape:(7172, 785)


The training dataset consists of 27455 28x28 pixel grayscale images, including the associated label. The testing dataset consists of 7172 28x28 images. The label and pixels are split into X and y for both training and testing data. 

In [7]:
#training data 
X_train = train.iloc[:,1:]
y_train = train.iloc[:,0]

#testing data
X_test = test.iloc[:,1:]
y_test = test.iloc[:,0]

The below is a function to find the indices of a specified label. 

In [8]:
#fuction to find the indices given a label 
def find_indices(data,label):
    #check if data is numpy array
    if type(data) == np.ndarray:
        #return indices
        return np.where(data==label)
    #check if data is pandas series 
    elif type(data) == pd.Series:
        #return indices
        return data[data==label].index
    #else not supported in this function
    else:
        raise Exception('Not supported data type for this function.')
        

Creating a dictionary where key is the numeric label in the dataset and value is the corresponding letter. 

In [9]:
#letters
letters = ['A','B','C','D','E','F','G','H','I','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y']
#numbers 
numbers = sorted(list(y_train.unique()))
#dictionary of labels 
labels = dict(zip(numbers,letters))

Inspecting examples for each letter in the dataset. 

In [10]:
#visualization of dataset 
fix, ax = plt.subplots(4,6)
ax = ax.ravel()
pos = 0 

#loop through each label in dataset 
for label in range(0,26):
    #if label is not included in dataset 
    if label in [9,25]:
        continue
    #find first index of label
    idx = find_indices(y_train,label)[0]
    #display first found image 
    ax[pos].imshow(X_train.iloc[idx,:].values.reshape(res),cmap='gray')
    #set x label as dataset label
    ax[pos].set(xlabel=labels[label])
    #do not show ticks 
    ax[pos].set_xticks([])
    ax[pos].set_yticks([])
    #increment for subplotting 
    pos+=1

plt.tight_layout()
plt.show()

No additional data loading and cleaning steps required for this dataset. 

In [11]:
#summary statistics
train.describe()

label        pixel1        pixel2        pixel3        pixel4  \
count  27455.000000  27455.000000  27455.000000  27455.000000  27455.000000   
mean      12.318813    145.419377    148.500273    151.247714    153.546531   
std        7.287552     41.358555     39.942152     39.056286     38.595247   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        6.000000    121.000000    126.000000    130.000000    133.000000   
50%       13.000000    150.000000    153.000000    156.000000    158.000000   
75%       19.000000    174.000000    176.000000    178.000000    179.000000   
max       24.000000    255.000000    255.000000    255.000000    255.000000   

             pixel5        pixel6        pixel7        pixel8        pixel9  \
count  27455.000000  27455.000000  27455.000000  27455.000000  27455.000000   
mean     156.210891    158.411255    160.472154    162.339683    163.954799   
std       37.111165     36.125579     35.016392     33.661998     32.651607   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%      137.000000    140.000000    142.000000    144.000000    146.000000   
50%      160.000000    162.000000    164.000000    165.000000    166.000000   
75%      181.000000    182.000000    183.000000    184.000000    185.000000   
max      255.000000    255.000000    255.000000    255.000000    255.000000   

       ...      pixel775      pixel776      pixel777      pixel778  \
count  ...  27455.000000  27455.000000  27455.000000  27455.000000   
mean   ...    141.104863    147.495611    153.325806    159.125332   
std    ...     63.751194     65.512894     64.427412     63.708507   
min    ...      0.000000      0.000000      0.000000      0.000000   
25%    ...     92.000000     96.000000    103.000000    112.000000   
50%    ...    144.000000    162.000000    172.000000    180.000000   
75%    ...    196.000000    202.000000    205.000000    207.000000   
max    ...    255.000000    255.000000    255.000000    255.000000   

           pixel779      pixel780      pixel781      pixel782      pixel783  \
count  27455.000000  27455.000000  27455.000000  27455.000000  27455.000000   
mean     161.969259    162.736696    162.906137    161.966454    161.137898   
std       63.738316     63.444008     63.509210     63.298721     63.610415   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%      120.000000    125.000000    128.000000    128.000000    128.000000   
50%      183.000000    184.000000    184.000000    182.000000    182.000000   
75%      208.000000    207.000000    207.000000    206.000000    204.000000   
max      255.000000    255.000000    255.000000    255.000000    255.000000   

           pixel784  
count  27455.000000  
mean     159.824731  
std       64.396846  
min        0.000000  
25%      125.500000  
50%      182.000000  
75%      204.000000  
max      255.000000  

[8 rows x 785 columns]

In [13]:
#plot the mean image
pixel_values = train.iloc[:,1:].values


var_image = np.var(pixel_values, axis=0)
plt.imshow(var_image.reshape(28,28), cmap='gray')
plt.title("Variance of the image")
plt.show()